/// Raw FFI bindings auto-generated by bindgen from MumblePlugin.h.
/// Contains type definitions AND function declarations — we only use the types.
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

use ffi::{
    mumble_channelid_t, mumble_connection_t, mumble_error_t, mumble_plugin_id_t,
    mumble_talking_state_t, mumble_mute_state_t, mumble_deaf_state_t,
    mumble_transmission_mode_t, mumble_settings_key_t,
    mumble_userid_t, mumble_version_t, Mumble_ErrorCode_MUMBLE_EC_OK,
    Mumble_TalkingState_MUMBLE_TS_PASSIVE, Mumble_TalkingState_MUMBLE_TS_TALKING,
    Mumble_TalkingState_MUMBLE_TS_TALKING_MUTED, Mumble_TalkingState_MUMBLE_TS_WHISPERING,
    Mumble_TalkingState_MUMBLE_TS_SHOUTING,
    Mumble_TransmissionMode_MUMBLE_TM_CONTINOUS,
    Mumble_TransmissionMode_MUMBLE_TM_VOICE_ACTIVATION,
    Mumble_TransmissionMode_MUMBLE_TM_PUSH_TO_TALK,
    Mumble_SettingsKey_MUMBLE_SK_AUDIO_INPUT_VOICE_HOLD,
    Mumble_SettingsKey_MUMBLE_SK_AUDIO_INPUT_VAD_SILENCE_THRESHOLD,
    Mumble_SettingsKey_MUMBLE_SK_AUDIO_INPUT_VAD_SPEECH_THRESHOLD,
    MumbleAPI_v_1_3_x, MumbleStringWrapper,
};

use bridge_types::{MumbleEvent, MumbleCommand, TalkingState, TransmissionMode, Channel, User};
use interprocess::local_socket::{prelude::*, GenericNamespaced, Stream};
use std::ffi::{c_void, CStr, CString};
use std::io::{BufRead, BufReader, BufWriter, Write};
use std::sync::{mpsc, Mutex};

const OK: mumble_error_t = Mumble_ErrorCode_MUMBLE_EC_OK as mumble_error_t;

static STATE: Mutex<Option<PluginState>> = Mutex::new(None);

struct PluginState {
    id: mumble_plugin_id_t,
    api: MumbleAPI_v_1_3_x,
    connection: Option<mumble_connection_t>,
    event_tx: Option<mpsc::Sender<MumbleEvent>>,
}

unsafe impl Send for PluginState {}

fn send_event(event: MumbleEvent) {
    let state = STATE.lock().unwrap();
    if let Some(ref s) = *state {
        if let Some(ref tx) = s.event_tx {
            let _ = tx.send(event);
        }
    }
}

fn mumble_log(msg: &str) {
    let state = STATE.lock().unwrap();
    if let Some(ref s) = *state {
        if let Ok(c_msg) = CString::new(msg) {
            unsafe { (s.api.log.unwrap())(s.id, c_msg.as_ptr()) };
        }
    }
}

fn static_string(s: &'static [u8]) -> MumbleStringWrapper {
    MumbleStringWrapper {
        data: s.as_ptr() as *const i8,
        size: s.len() - 1,
        needsReleasing: false,
    }
}

// ==================== MANDATORY PLUGIN FUNCTIONS ====================

#[no_mangle]
pub extern "C" fn mumble_registerAPIFunctions(api_struct: *mut c_void) {
    let api = unsafe { *(api_struct as *mut MumbleAPI_v_1_3_x) };
    let mut state = STATE.lock().unwrap();
    *state = Some(PluginState {
        id: 0,
        api,
        connection: None,
        event_tx: None,
    });
}

#[no_mangle]
pub extern "C" fn mumble_init(id: mumble_plugin_id_t) -> mumble_error_t {
    let mut state = STATE.lock().unwrap();
    let Some(ref mut s) = *state else {
        return OK;
    };
    s.id = id;

    if let Ok(msg) = CString::new("etch-bridge plugin loaded") {
        unsafe { (s.api.log.unwrap())(s.id, msg.as_ptr()) };
    }

    let sock_name = match std::env::var("ETCH_BRIDGE_SOCK") {
        Ok(name) => name,
        Err(_) => {
            // No socket configured — plugin runs in passive mode (log only).
            return OK;
        }
    };

    let (event_tx, event_rx) = mpsc::channel();
    s.event_tx = Some(event_tx);

    let api = s.api;
    let plugin_id = s.id;

    std::thread::spawn(move || {
        if let Err(e) = ipc_thread(sock_name, event_rx, api, plugin_id) {
            eprintln!("[etch-bridge] IPC thread error: {}", e);
        }
    });

    OK
}

#[no_mangle]
pub extern "C" fn mumble_shutdown() {
    let mut state = STATE.lock().unwrap();
    if let Some(ref mut s) = *state {
        // Drop the sender so the IPC writer loop exits.
        s.event_tx = None;
    }
}

#[no_mangle]
pub extern "C" fn mumble_getName() -> MumbleStringWrapper {
    static_string(b"Etch Bridge\0")
}

#[no_mangle]
pub extern "C" fn mumble_getVersion() -> mumble_version_t {
    mumble_version_t {
        major: env!("CARGO_PKG_VERSION_MAJOR").parse().unwrap_or(0),
        minor: env!("CARGO_PKG_VERSION_MINOR").parse().unwrap_or(0),
        patch: env!("CARGO_PKG_VERSION_PATCH").parse().unwrap_or(0),
    }
}

#[no_mangle]
pub extern "C" fn mumble_getAuthor() -> MumbleStringWrapper {
    static_string(b"Guillermo Briceno\0")
}

#[no_mangle]
pub extern "C" fn mumble_getDescription() -> MumbleStringWrapper {
    static_string(b"Bridge to the Etch client\0")
}

#[no_mangle]
pub extern "C" fn mumble_getAPIVersion() -> mumble_version_t {
    mumble_version_t { major: 1, minor: 3, patch: 0 }
}

#[no_mangle]
pub extern "C" fn mumble_getPluginFunctionsVersion() -> mumble_version_t {
    mumble_version_t { major: 1, minor: 1, patch: 0 }
}

#[no_mangle]
pub extern "C" fn mumble_getFeatures() -> u32 { 0 }

#[no_mangle]
pub extern "C" fn mumble_deactivateFeatures(_features: u32) -> u32 { 0 }

#[no_mangle]
pub extern "C" fn mumble_releaseResource(_pointer: *const c_void) {}

// ==================== CALLBACKS ====================

#[no_mangle]
pub extern "C" fn mumble_onServerConnected(_connection: mumble_connection_t) {
    send_event(MumbleEvent::ServerConnected);
}

#[no_mangle]
pub extern "C" fn mumble_onServerSynchronized(connection: mumble_connection_t) {
    let mut state = STATE.lock().unwrap();
    let Some(ref mut s) = *state else { return };
    s.connection = Some(connection);

    let event = build_server_sync(s, connection);
    if let Some(ref tx) = s.event_tx {
        let _ = tx.send(event);

        // Send initial settings
        if let Some(mode) = query_transmission_mode(s) {
            let _ = tx.send(MumbleEvent::TransmissionModeChanged { mode });
        }
        if let Some(value) = query_setting_double(s, Mumble_SettingsKey_MUMBLE_SK_AUDIO_INPUT_VAD_SPEECH_THRESHOLD as mumble_settings_key_t) {
            let _ = tx.send(MumbleEvent::VadThresholdChanged { value });
        }
        if let Some(value) = query_setting_int(s, Mumble_SettingsKey_MUMBLE_SK_AUDIO_INPUT_VOICE_HOLD as mumble_settings_key_t) {
            let _ = tx.send(MumbleEvent::VoiceHoldChanged { value });
        }
    }
}

#[no_mangle]
pub extern "C" fn mumble_onServerDisconnected(_connection: mumble_connection_t) {
    {
        let mut state = STATE.lock().unwrap();
        if let Some(ref mut s) = *state {
            s.connection = None;
        }
    }
    send_event(MumbleEvent::ServerDisconnected);
}

#[no_mangle]
pub extern "C" fn mumble_onUserAdded(connection: mumble_connection_t, user_id: mumble_userid_t) {
    let state = STATE.lock().unwrap();
    let Some(ref s) = *state else { return };
    if s.connection.is_none() { return; }

    if let Some(user) = build_user(s, connection, user_id) {
        if let Some(ref tx) = s.event_tx {
            let _ = tx.send(MumbleEvent::UserConnected { user });
        }
    }
}

#[no_mangle]
pub extern "C" fn mumble_onUserRemoved(_connection: mumble_connection_t, user_id: mumble_userid_t) {
    let state = STATE.lock().unwrap();
    let Some(ref s) = *state else { return };
    if s.connection.is_none() { return; }

    if let Some(ref tx) = s.event_tx {
        let _ = tx.send(MumbleEvent::UserDisconnected { session: user_id });
    }
}

#[no_mangle]
pub extern "C" fn mumble_onChannelEntered(
    _connection: mumble_connection_t,
    user_id: mumble_userid_t,
    _previous_channel_id: mumble_channelid_t,
    new_channel_id: mumble_channelid_t,
) {
    let state = STATE.lock().unwrap();
    let Some(ref s) = *state else { return };
    if s.connection.is_none() { return; }

    if let Some(ref tx) = s.event_tx {
        let _ = tx.send(MumbleEvent::UserMoved {
            session: user_id,
            channel_id: new_channel_id,
        });
    }
}

#[no_mangle]
pub extern "C" fn mumble_onChannelExited(
    _connection: mumble_connection_t,
    _user_id: mumble_userid_t,
    _channel_id: mumble_channelid_t,
) {
    // UserMoved from onChannelEntered covers this — the user enters a new channel.
    // If the user disconnects, onUserRemoved handles it.
}

#[no_mangle]
pub extern "C" fn mumble_onChannelAdded(connection: mumble_connection_t, channel_id: mumble_channelid_t) {
    let state = STATE.lock().unwrap();
    let Some(ref s) = *state else { return };
    if s.connection.is_none() { return; }

    if let Some(channel) = build_channel(s, connection, channel_id) {
        if let Some(ref tx) = s.event_tx {
            let _ = tx.send(MumbleEvent::ChannelAdded { channel });
        }
    }
}

#[no_mangle]
pub extern "C" fn mumble_onChannelRemoved(_connection: mumble_connection_t, channel_id: mumble_channelid_t) {
    let state = STATE.lock().unwrap();
    let Some(ref s) = *state else { return };
    if s.connection.is_none() { return; }

    if let Some(ref tx) = s.event_tx {
        let _ = tx.send(MumbleEvent::ChannelRemoved { id: channel_id });
    }
}

#[no_mangle]
pub extern "C" fn mumble_onChannelRenamed(connection: mumble_connection_t, channel_id: mumble_channelid_t) {
    let state = STATE.lock().unwrap();
    let Some(ref s) = *state else { return };
    if s.connection.is_none() { return; }

    unsafe {
        if let Some(name) = get_string(&s.api, s.id, |a, out| {
            (a.getChannelName.unwrap())(s.id, connection, channel_id, out)
        }) {
            if let Some(ref tx) = s.event_tx {
                let _ = tx.send(MumbleEvent::ChannelRenamed { id: channel_id, name });
            }
        }
    }
}

#[no_mangle]
pub extern "C" fn mumble_onUserTalkingStateChanged(
    _connection: mumble_connection_t,
    user_id: mumble_userid_t,
    talking_state: mumble_talking_state_t,
) {
    let state = STATE.lock().unwrap();
    let Some(ref s) = *state else { return };
    if s.connection.is_none() { return; }

    #[allow(non_upper_case_globals)]
    let bridge_state = match talking_state {
        Mumble_TalkingState_MUMBLE_TS_PASSIVE => TalkingState::Passive,
        Mumble_TalkingState_MUMBLE_TS_TALKING => TalkingState::Talking,
        Mumble_TalkingState_MUMBLE_TS_WHISPERING => TalkingState::Whispering,
        Mumble_TalkingState_MUMBLE_TS_SHOUTING => TalkingState::Shouting,
        Mumble_TalkingState_MUMBLE_TS_TALKING_MUTED => TalkingState::TalkingMuted,
        _ => return,
    };

    if let Some(ref tx) = s.event_tx {
        let _ = tx.send(MumbleEvent::UserTalking { session: user_id, state: bridge_state });
    }
}

#[no_mangle]
pub extern "C" fn mumble_onUserMuteStateChanged(
    _connection: mumble_connection_t,
    user_id: mumble_userid_t,
    mute_state: mumble_mute_state_t,
) {
    let state = STATE.lock().unwrap();
    let Some(ref s) = *state else { return };
    if s.connection.is_none() { return; }

    if let Some(ref tx) = s.event_tx {
        let _ = tx.send(MumbleEvent::UserMuteStateChanged {
            session: user_id,
            mute_state: mute_state as u32,
        });
    }
}

#[no_mangle]
pub extern "C" fn mumble_onUserDeafStateChanged(
    _connection: mumble_connection_t,
    user_id: mumble_userid_t,
    deaf_state: mumble_deaf_state_t,
) {
    let state = STATE.lock().unwrap();
    let Some(ref s) = *state else { return };
    if s.connection.is_none() { return; }

    if let Some(ref tx) = s.event_tx {
        let _ = tx.send(MumbleEvent::UserDeafStateChanged {
            session: user_id,
            deaf_state: deaf_state as u32,
        });
    }
}

// ==================== IPC ====================

fn ipc_thread(
    sock_name: String,
    event_rx: mpsc::Receiver<MumbleEvent>,
    api: MumbleAPI_v_1_3_x,
    plugin_id: mumble_plugin_id_t,
) -> std::io::Result<()> {
    mumble_log(&format!("[etch-bridge] Connecting to {}", sock_name));

    let name = sock_name.to_ns_name::<GenericNamespaced>()?;
    let stream = Stream::connect(name)?;

    let (recv, send) = stream.split();

    // Reader thread — receives commands from etch-core
    std::thread::spawn(move || {
        let reader = BufReader::new(recv);
        for line in reader.lines() {
            let line = match line {
                Ok(l) => l,
                Err(_) => break,
            };
            if line.is_empty() { continue; }
            match serde_json::from_str::<MumbleCommand>(&line) {
                Ok(cmd) => execute_command(api, plugin_id, &cmd),
                Err(e) => eprintln!("[etch-bridge] Bad command: {}", e),
            }
        }
    });

    // Writer loop — sends events to etch-core
    let mut writer = BufWriter::new(send);
    for event in event_rx {
        if let Ok(json) = serde_json::to_string(&event) {
            let _ = writer.write_all(json.as_bytes());
            let _ = writer.write_all(b"\n");
            let _ = writer.flush();
        }
    }

    Ok(())
}

fn execute_command(api: MumbleAPI_v_1_3_x, plugin_id: mumble_plugin_id_t, cmd: &MumbleCommand) {
    // Read connection from STATE, then drop the lock before calling API.
    // API calls are RPC'd to Mumble's main thread — holding the lock would deadlock
    // if a callback fires and tries to lock STATE.
    let connection = {
        let state = STATE.lock().unwrap();
        state.as_ref().and_then(|s| s.connection)
    };
    let Some(connection) = connection else { return };

    unsafe {
        match cmd {
            MumbleCommand::SwitchChannel { channel_id } => {
                let mut local_id: mumble_userid_t = 0;
                if (api.getLocalUserID.unwrap())(plugin_id, connection, &mut local_id) != OK {
                    return;
                }
                (api.requestUserMove.unwrap())(plugin_id, connection, local_id, *channel_id, std::ptr::null());
            }
            MumbleCommand::SetMuted { muted } => {
                (api.requestLocalUserMute.unwrap())(plugin_id, *muted);
            }
            MumbleCommand::SetDeafened { deafened } => {
                (api.requestLocalUserDeaf.unwrap())(plugin_id, *deafened);
            }
            MumbleCommand::SetUserVolume { session, volume } => {
                (api.setUserLocalVolumeAdjustment.unwrap())(plugin_id, connection, *session, *volume);
            }
            MumbleCommand::SetTransmissionMode { mode } => {
                #[allow(non_upper_case_globals)]
                let tm = match mode {
                    TransmissionMode::Continuous => Mumble_TransmissionMode_MUMBLE_TM_CONTINOUS,
                    TransmissionMode::VoiceActivation => Mumble_TransmissionMode_MUMBLE_TM_VOICE_ACTIVATION,
                    TransmissionMode::PushToTalk => Mumble_TransmissionMode_MUMBLE_TM_PUSH_TO_TALK,
                };
                (api.requestLocalUserTransmissionMode.unwrap())(plugin_id, tm);
            }
            MumbleCommand::SetVadThreshold { value } => {
                // Set both silence and speech thresholds to the same value
                (api.setMumbleSetting_double.unwrap())(
                    plugin_id,
                    Mumble_SettingsKey_MUMBLE_SK_AUDIO_INPUT_VAD_SILENCE_THRESHOLD as mumble_settings_key_t,
                    *value,
                );
                (api.setMumbleSetting_double.unwrap())(
                    plugin_id,
                    Mumble_SettingsKey_MUMBLE_SK_AUDIO_INPUT_VAD_SPEECH_THRESHOLD as mumble_settings_key_t,
                    *value,
                );
            }
            MumbleCommand::SetVoiceHold { value } => {
                (api.setMumbleSetting_int.unwrap())(
                    plugin_id,
                    Mumble_SettingsKey_MUMBLE_SK_AUDIO_INPUT_VOICE_HOLD as mumble_settings_key_t,
                    *value,
                );
            }
        }
    }
}

// ==================== QUERY HELPERS ====================

fn build_server_sync(s: &PluginState, connection: mumble_connection_t) -> MumbleEvent {
    let mut local_session: mumble_userid_t = 0;
    unsafe { (s.api.getLocalUserID.unwrap())(s.id, connection, &mut local_session); }
    let channels = query_all_channels(s, connection);
    let users = query_all_users(s, connection);
    MumbleEvent::ServerSync { local_session, channels, users }
}

fn query_all_channels(s: &PluginState, connection: mumble_connection_t) -> Vec<Channel> {
    unsafe {
        let mut ptr: *mut mumble_channelid_t = std::ptr::null_mut();
        let mut count: usize = 0;
        if (s.api.getAllChannels.unwrap())(s.id, connection, &mut ptr, &mut count) != OK {
            return Vec::new();
        }

        let mut channels = Vec::with_capacity(count);
        for i in 0..count {
            let ch_id = *ptr.add(i);
            if let Some(ch) = build_channel(s, connection, ch_id) {
                channels.push(ch);
            }
        }
        (s.api.freeMemory.unwrap())(s.id, ptr as *const c_void);
        channels
    }
}

fn query_all_users(s: &PluginState, connection: mumble_connection_t) -> Vec<User> {
    unsafe {
        let mut ptr: *mut mumble_userid_t = std::ptr::null_mut();
        let mut count: usize = 0;
        if (s.api.getAllUsers.unwrap())(s.id, connection, &mut ptr, &mut count) != OK {
            return Vec::new();
        }

        let mut users = Vec::with_capacity(count);
        for i in 0..count {
            let uid = *ptr.add(i);
            if let Some(u) = build_user(s, connection, uid) {
                users.push(u);
            }
        }
        (s.api.freeMemory.unwrap())(s.id, ptr as *const c_void);
        users
    }
}

fn build_user(s: &PluginState, connection: mumble_connection_t, user_id: mumble_userid_t) -> Option<User> {
    unsafe {
        let name = get_string(&s.api, s.id, |a, out| {
            (a.getUserName.unwrap())(s.id, connection, user_id, out)
        })?;

        let mut channel_id: mumble_channelid_t = 0;
        if (s.api.getChannelOfUser.unwrap())(s.id, connection, user_id, &mut channel_id) != OK {
            return None;
        }

        let mut mute_state: ffi::mumble_mute_state_t = 0;
        let mut deaf_state: ffi::mumble_deaf_state_t = 0;
        let mut volume_adjustment: f32 = 1.0;
        (s.api.getUserMuteState.unwrap())(s.id, connection, user_id, &mut mute_state);
        (s.api.getUserDeafState.unwrap())(s.id, connection, user_id, &mut deaf_state);
        (s.api.getUserLocalVolumeAdjustment.unwrap())(s.id, connection, user_id, &mut volume_adjustment);

        Some(User {
            session: user_id,
            name,
            channel_id,
            mute_state: mute_state as u32,
            deaf_state: deaf_state as u32,
            volume_adjustment,
        })
    }
}

fn query_setting_double(s: &PluginState, key: mumble_settings_key_t) -> Option<f64> {
    unsafe {
        let mut value: f64 = 0.0;
        if (s.api.getMumbleSetting_double.unwrap())(s.id, key, &mut value) != OK {
            return None;
        }
        Some(value)
    }
}

fn query_setting_int(s: &PluginState, key: mumble_settings_key_t) -> Option<i64> {
    unsafe {
        let mut value: i64 = 0;
        if (s.api.getMumbleSetting_int.unwrap())(s.id, key, &mut value) != OK {
            return None;
        }
        Some(value)
    }
}

fn query_transmission_mode(s: &PluginState) -> Option<TransmissionMode> {
    unsafe {
        let mut tm: mumble_transmission_mode_t = 0;
        if (s.api.getLocalUserTransmissionMode.unwrap())(s.id, &mut tm) != OK {
            return None;
        }
        #[allow(non_upper_case_globals)]
        let mode = match tm {
            Mumble_TransmissionMode_MUMBLE_TM_CONTINOUS => TransmissionMode::Continuous,
            Mumble_TransmissionMode_MUMBLE_TM_PUSH_TO_TALK => TransmissionMode::PushToTalk,
            _ => TransmissionMode::VoiceActivation,
        };
        Some(mode)
    }
}

fn build_channel(s: &PluginState, connection: mumble_connection_t, channel_id: mumble_channelid_t) -> Option<Channel> {
    unsafe {
        let name = get_string(&s.api, s.id, |a, out| {
            (a.getChannelName.unwrap())(s.id, connection, channel_id, out)
        })?;

        // TODO: parent channel ID — API doesn't expose this directly.
        // For now, use 0 as placeholder.
        Some(Channel { id: channel_id, name, parent: 0 })
    }
}

// ==================== FFI HELPERS ====================

unsafe fn get_string(
    api: &MumbleAPI_v_1_3_x,
    plugin_id: mumble_plugin_id_t,
    f: impl FnOnce(&MumbleAPI_v_1_3_x, &mut *const i8) -> mumble_error_t,
) -> Option<String> {
    let mut ptr: *const i8 = std::ptr::null();
    if f(api, &mut ptr) != OK {
        return None;
    }
    let s = CStr::from_ptr(ptr).to_string_lossy().into_owned();
    (api.freeMemory.unwrap())(plugin_id, ptr as *const c_void);
    Some(s)
}
